### ISSUE TITLE
你好，怎么改成6为非密码输入框

### ISSUE THREAD

**Issue by wengxianxun** [evan2020/six-Input-box#1]
如题，我想改成同样是6位可见文本的输入框

**Comment by wengxianxun** [comment]
题主在吗

**Comment by evan2020** [comment]
@wengxianxun 
才看到

1.首先取消 圆点 的样式
2.然后往每个格式中间加一个容器（view/text之类的）
3.把每次输入的内容放在数组中（一般一个数字/字符一次输入）
4.一个格子内容对应一个数组的某一项（按顺序排列）

就可以了

**Comment by evan2020** [comment]
@wengxianxun 
有空我再更新明文内容输入框，还是代码见效果

**Comment by evan2020** [comment]
@wengxianxun

已改为可选明文显示
代码片段地址：wechatide://minicode/ejANw6mJ6uY5
引入小程序查看效果即可

**Comment by wengxianxun** [comment]
谢谢
