### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by leaf1992** [evan2020/six-Input-box#2]
![c462b88b-8044-406d-a049-c46033253f67](https://user-images.githubusercontent.com/13012378/40958060-7ed4a1a2-68ca-11e8-8251-e3f2b6ac7fb3.png)
在unLoad里加入了这个也报错
this.paySix = this.selectComponent('#paySix')

**Comment by evan2020** [comment]
@leaf1992 
记得查看代码片段地址：wechatide://minicode/uSYM88mq6lYa（并无错误）
对照代码片段拷贝代码，并保证在你的项目里文件路径正确，貌似我的项目没有大写的Component
