### ISSUE TITLE
请问输入的值怎么获得

### ISSUE THREAD

**Issue by Ciiiiing** [evan2020/six-Input-box#3]
在index界面如何获得输入的值呢

**Comment by evan2020** [comment]
仔细看官方文档和输入框的源码注释
**component.js中**
![注释](https://om83cysj8.qnssl.com/4445.png)
因为场景需求，参数我没用所以没写，但是它的确是传递过来了
**index.js中**
![参数](https://om83cysj8.qnssl.com/Snipaste_2018-06-14_16-20-41.png)
获取对应字段即可

**Comment by evan2020** [comment]
@Ciiiiing 多看注释
