### ISSUE TITLE
建议封装一个初始化的函数来调用组件

### ISSUE THREAD

**Issue by super456** [evan2020/six-Input-box#4]
主要是方便需要点击支付的时候再初始化并调用组件来使用。（该组件比较适用于弹窗形式）
目前只能做的是进入确认支付页面（父级）不能设置js的data中：inputData（输入框参数设置），否则再弹出这个输入框就输入不了数据，因为数据中的value_length:0已经被使用过了（组件逻辑那里处理不了了）,目前解决方法是在进入页面的时候不设置，需要的时候调用函数定义data中inputData（输入框参数设置）相当于初始化了，所以还是建议在原组件包装一下初始化函数，父级只需要在用到的时候初始化就可以用了。:smile:

**Comment by evan2020** [comment]
@super456 
谢谢建议，这个是一个在很久前工作中用到的组件demo，起的是一个抛砖引玉的作用
闲下来的时候再优化.....

**Comment by super456** [comment]
挺好的，给我很多启发，也学到了很多东西。
