### ISSUE TITLE
密码输入框,在苹果7手机上获焦无法弹出键盘

### ISSUE THREAD

**Issue by wangdong1209** [evan2020/six-Input-box#5]

**Comment by cleocn** [comment]
今天客户说oppo手机也不行。急

**Comment by SkyGrass** [comment]
iphone6s 以及部分android 机也有这个问题

**Comment by calmgo** [comment]
经过测试，发现在微信新版本7.0.3上出现了这个bug。

component.wxss
/* 输入框 */

.input_container {
  /* height: 0;
  width: 0; */
  min-height: 0;
  position: relative;
  text-indent: -999em;
  left: -100%;
}

注销掉这两行就可以了。

参考：
https://developers.weixin.qq.com/community/develop/doc/00046ac5eb48d03c7f48e32ec56800?highLine=%25E9%2594%25AE%25E7%259B%2598

**Comment by evan2020** [comment]
@SkyGrass @wangdong1209 @cleocn 没有相关机型复现,请参考4楼网友的答案

component.wxss
/* 输入框 */

.input_container {
/* height: 0;
width: 0; */
min-height: 0;
position: relative;
text-indent: -999em;
left: -100%;
}

注销掉这两行就可以了。

参考：
https://developers.weixin.qq.com/community/develop/doc/00046ac5eb48d03c7f48e32ec56800?highLine=%25E9%2594%25AE%25E7%259B%2598

**Comment by evan2020** [comment]
@calmgo 谢谢

**Comment by wangdong1209** [comment]
多谢4楼
